version: 2

sources:
  - name: main
    tables:
      - name: raw_ipc
        meta:
          dagster:
            asset_key: ["raw_ipc"]
      - name: raw_hipotecas
        meta:
          dagster:
            asset_key: ["raw_hipotecas"]
