[project]
name = "datania"
version = "1.0.0"
description = "Plataforma de datos abiertos para unificar y armonizar información proveniente de diferentes fuentes."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster>=1.9.3",
    "dagster-duckdb>=0.25.3",
    "dagster-duckdb-polars>=0.25.3",
    "duckdb>=1.1.3",
    "httpx>=0.28.1",
    "huggingface-hub>=0.27.0",
    "polars>=1.18.0",
    "pyarrow>=18.1.0",
    "tenacity>=9.0.0",
]

[dependency-groups]
dev = ["dagster-webserver>=1.9.3", "ipykernel>=6.29.5", "ruff>=0.8.4"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["datania"]

[tool.dagster]
module_name = "datania.definitions"
code_location_name = "datania"
