[project]
name = "datania"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster>=1.8.8",
    "duckdb>=1.1.1",
    "dagster-dbt>=0.24.8",
    "dagster-duckdb>=0.24.8",
    "dbt-duckdb>=1.8.3",
    "ipykernel>=6.29.5",
    "pyarrow>=17.0.0",
    "dagster-duckdb-polars>=0.24.8",
    "polars>=1.8.1",
    "huggingface-hub>=0.25.1",
    "httpx>=0.27.2",
    "tenacity>=9.0.0",
]

[tool.setuptools]
packages = ["datania"]

[tool.dagster]
module_name = "datania.definitions"
code_location_name = "datania"

[tool.uv]
dev-dependencies = ["dagster-webserver>=1.8.6"]
