name: ETL

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
    inputs:
      upload_db:
        description: 'Upload database to release'
        required: true
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      AEMET_API_TOKEN: ${{ secrets.AEMET_API_TOKEN }}
      ENVIRONMENT: production
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Run
        run: |
          make run

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload database to release
        if: github.event_name == 'schedule' || inputs.upload_db == true
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.date.outputs.date }}
          file: data/database.duckdb
          asset_name: datania.duckdb
          overwrite: true
          release_name: ${{ steps.date.outputs.date }}
