name: ETL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      AEMET_API_TOKEN: ${{ secrets.AEMET_API_TOKEN }}
      ENVIRONMENT: production
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Run
        run: |
          make run
